### ISSUE TITLE
Adding authorizations to new members via Member/Detail interface throws an exception

### ISSUE THREAD

**Issue by tanaes** [ithacagenerator/AuthBox#26]
It is possible to add members of type "new" (i.e. signed up in the last month) to authboxes via the Authbox/Detail/(+) dialogue, but trying to add the authorization directly to the member via the Member/Detail/(+) dialogue throws an exception and prevents further interaction with the interface.

**Comment by vicatcu** [comment]
fixed by db9fc3e4cfd1974da73682fc40fdca298dc5a4ac
